Revert "Unbreak the cluster destroy job"
This reverts commit 307f8a3cf8066c24dde4c16ed8fef57a7053fc70.

Error: Variables not allowed

Variables may not be used here.

https://github.com/hashicorp/terraform/issues/3116