Fix gsp-local error due to empty values in harbor-notary-secret.yaml
- GSP Local users were getting the following error message due to these
  values being empty:
  ```
  error: error validating "/var/folders/jr/lv1mpg4s6cgby621kx99vjfm0000gr/T/tmp.oZlkGF5l/gsp-cluster/templates/02-gsp-system/harbor-notary-secret.yaml": error validating data: [unknown object type "nil" in Secret.data.ca, unknown object type "nil" in Secret.data.crt, unknown object type "nil" in Secret.data.key, unknown object type "nil" in Secret.data.tls.ca, unknown object type "nil" in Secret.data.tls.crt, unknown object type "nil" in Secret.data.tls.key]
  ```
- The problem is b64enc requires a non-empty string, and it's getting
  just that from charts/gsp-cluster/values.yaml.
- Outside of GSP Local, these values are loaded from Terraform. But
  within GSP Local, Terraform doesn't run.

Co-authored-by: Joakim Kakaei <joakim.kakaei@digital.cabinet-office.gov.uk>